name: Tag Created Workflow
on:
  push:
    tags:
      - '*'

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
        
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        # login to docker hub
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
              context: .
              push: true
              # push with just the tag
              tags: zalfrpm/monica-cluster:${{ github.ref_name }}    

        - name: Create GitHub release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: false