name: Tag Created Workflow
on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build the Docker image
          # build docker image, to check if it works
          run: docker build . --file Dockerfile --tag zalfrpm/monica-cluster:$(date +%s)
            # push docker image to docker hub

        # login to docker hub
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
              context: .
              push: true
              tags: zalfrpm/monica-cluster:${{ github.ref }}    

        - name: Create GitHub release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: false